services:
  stable-diffusion: 
    build: .
    ports:
      - "5002:5002"
    ipc: host
    stdin_open: true
    tty: true
    volumes:
      - ./:/stable-diffusion
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
